"""add chunk embeddings

Revision ID: 19d25482e720
Revises: 852e9ecfa992
Create Date: 2026-08-16 22:33:37.952899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d25482e720'
down_revision: Union[str, Sequence[str], None] = '852e9ecfa992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("chunks", "embedding")
    # ### end Alembic commands ###
